name: terraform infra

on:
  workflow_dispatch:

jobs:
  terraform_init:
    name: terraform init
    runs-on: self-hosted
    steps:
       - name: Terraform installer
         uses: autero1/action-terraform@v3.0.1
         with:
           terraform-version: latest
       - name: Terraform Init
         run: terraform init 
      
              
              
        
 
          

