name: terraform infra

on:
  workflow_dispatch:
  
permissions:
  actions: read
  checks: read

jobs:
  terraform_init:
    name: terraform init
    runs-on: self-hosted
    steps:
       - name: Checkout repo
         uses: actions/checkout@v3
       # - name: Terraform installer
       #   uses: autero1/action-terraform@v3.0.1
       #   with:
       #     terraform-version: latest
       - name: Check Terraform Version
         run: terraform version
       - name: Terraform Init
         run: terraform init 
         
      
              
              
        
 
          

